### ISSUE TITLE
Warning: trim() expects parameter 1 to be string, array given in plugin scriptmerge

### ISSUE THREAD

**Issue by ghost** [yireo/pkg_scriptmerge#1]
Above warning 
- in version 0.9.23 in line 872
- in version 0.9.24 in line 896

Reason:

```
$this->getArrayFromParam('exclude_menuitems');
```

results in an array. Field exclude_menuitems is a multiple one.

See

```
private function getArrayFromParam($param)
{
$data = $this->params->get($param);
$data = trim($data);
...
```

**Comment by yireo** [comment]
Thanks for posting. Your comments were already so much in detail - I thought you were also going to add a code fix :) I've added a fix for it now.

**Comment by ghost** [comment]
>  I thought you were also going to add a code fix :)

I don't use this plugin. Thus I couldn't test an own Pull Request.  Just found the error indexed at Google. So, you and I made some anonymous users happy, ;-).
