### ISSUE TITLE
Leverage browser caching

### ISSUE THREAD

**Issue by AlexanderSk** [yireo/pkg_scriptmerge#10]
Hello again.
I found sometime and i am trying to find google page speed insights for a website with this plugin.
What i am getting from google is a "Laverage broswer caching" fix consideration for the css and javascript pages that are shown with 30 minutes caching time.

The settings:
Merge Type: File-list Dynamic
Hashing method: Advanced

Now what is the issue / s
I have a multy language site that requires dynamic hashing and thus these are the settings.
Since the htaccess doesnt see the .css or .js file type doesnt give these two files correct time to expire.

I tried to add the extensions manually in the plugin with no success, also this could be done perhaps via php from the components view as it gets called but i cant seem to find the view...
Any assistance / thoughts?

Edit: I tried editing the com_scriptmerge\helpers\helper.php without any results.

**Comment by AlexanderSk** [comment]
Issue solved by setting in the advanced section Maximum time: 10080 (7 days ).
Really nice i did remember this option at all... By the way what does Create Data URis is for?

**Comment by yireo** [comment]
Data URIs are explained here: https://en.wikipedia.org/wiki/Data_URI_scheme The setting in ScriptMerge allows images to be translated to data URIs, increasing the body size of the HTML document but decreasing the number of HTTP requests.
